name: Tests

on:
  pull_request:
    branches: [ main ]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    environment: contribution

    strategy:
      matrix:
        version:
          - '2.26'
          - '2.26-pro'
          # 3.0 Gold Master doesn't work properly atm with Linux and Xvfb
          # - 'current'
          # - 'current-pro'

    steps:
      - uses: actions/checkout@v2
      - name: Download dragonruby
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-1
          DRAGONRUBY_VERSION: ${{ matrix.version }}
        run: |
          aws s3 cp s3://kf-dragonruby/font.ttf .
          aws s3 cp s3://kf-dragonruby/$DRAGONRUBY_VERSION/dragonruby .
          chmod u+x ./dragonruby
      - name: Run tests
        run: |
          SDL_VIDEODRIVER=dummy ./dragonruby game --test tests/main.rb | tee test-output.txt
          grep '0 test(s) failed' test-output.txt # Workaround since dragonruby does not return failed exit status
